version: '3.8'
services:             
    cosc304-mysql:
        image: mysql:8.0
        container_name: cosc304-mysql
        restart: always
        environment:
            MYSQL_DATABASE: 'testuser'
            MYSQL_USER: 'testuser'
            MYSQL_PASSWORD: '304testpw'            
            MYSQL_ROOT_PASSWORD: '304rootpw'
        ports:
            - '3306:3306'
        expose:
            - '3306'   
        volumes:
            - mysql-db:/var/lib/mysql
            - ./ddl:/docker-entrypoint-initdb.d
    cosc304-sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: cosc304-sqlserver
        restart: always
        environment:
            ACCEPT_EULA: 'Y'
            SA_PASSWORD: '304#sa#pw'
        ports:
            - '1433:1433'
        expose:
            - '1433'
        volumes:
            - cosc304-db:/var/lib/mssql
volumes: 
    cosc304-db:
    mysql-db:
